sudo: required

language: go

go:
  - master

services:
  - docker

before_install:
  - mkdir -p /dockerfiles/{go,robot}
  - mkdir -p /robot/{tests,reports}
  - curl https://github.com/manziman/test_go_web/dockerfile/Dockerfile >> dockerfiles/go/Dockerfile
  - docker build -t test-go /dockerfiles/go
  - docker network create --attachable test-go
  - docker run -d --rm --name go-server -p 9090:9090 --network test-go
  - docker ps -a

script:
  - go test
  - curl https://github.com/manziman/dockercistack/blob/master/dockerfiles/robot-server/Dockerfile >> dockerfiles/go/robot/Dockerfile
  - docker build -t test-robot /dockerfiles/robot
  - docker run -t --rm --name robot-server --network test-go -v /robot/reports:/opt/robotframework/reports -v /robot/tests:/opt/robotframework/tests test-robot -d /opt/robotframework/reports/ /opt/robotframework/tests/
